version: "3"

services:
  # api:
  #   build:
  #     context: ${API_PATH}
  #     target: dev
  #   ports:
  #     - "3030:3030"
  #   environment:
  #     POSTGRES_HOST: "db"
  #     DATABASE_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}"
  #     REDIS_HOST: cache
  #     REDIS_PORT: 6379
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}

  #   depends_on:
  #     - db
  #     - cache
  #   restart: on-failure
  #   volumes:
  #     - ./src:/api/src
  #     - ./config:/api/config
  #     - ./test:/api/test
  #     - ./public:/api/public
  #   networks:
  #     - conection-db
  #     - connection-cache

  db:
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}  
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - conection-db
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  conection-db:
  connection-cache:

volumes:
  db-data:
  cache:

