name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # or whatever version you need

      - name: Install dependencies
        run: cd server && yarn install

      - name: Build
        run: cd server && yarn run compile

  build-front:
    needs: build-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # or whatever version you need

      - name: Install dependencies
        run: cd client && yarn install

      - name: Build
        run: cd client && yarn run build

  # test:
  #   needs: build-front
  #   runs-on: ubuntu-latest
  #   services:
  #     postgres:
  #       image: postgres:13
  #       env:
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: postgres
  #         POSTGRES_DB: testdb
  #       ports:
  #         - 5432:5432
  #       # needed because the postgres container does not provide a healthcheck
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Use Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "20" # or whatever version you need

  #     - name: Install dependencies
  #       run: yarn install

  #     - name: Test
  #       run: yarn run test
  #       env:
  #         DATABASE_URL: postgres://postgres:postgres@localhost:5432/testdb
